name: Terraform Plan

on:
  pull_request:

env:
  STATE_BUCKET: tf-state-8864
  PROJECT_NAME: frontend-health-check
  AWS_REGION: us-east-1
  ENVIRONMENT: development

jobs:
  terraform:
    runs-on: ubuntu-latest
    # environment: ${{ env.ENVIRONMENT }}
    permissions:
      contents: read
      pull-requests: write
    defaults:
      run:
        working-directory: ./terraform
    steps:
    - name: Terraform Plan
      id: terraform-plan
      uses: mleager/tf-shared-actions/.github/actions/terraform-plan@main
      with:
        bucket: ${{ env.STATE_BUCKET }}
        key: ${{ env.PROJECT_NAME }}/terraform.tfstate
        region: ${{ env.AWS_REGION }}
        var_file: terraform.tfvars.${{ env.ENVIRONMENT }}
        make_pr_comment: true
        github_token: ${{ secrets.GITHUB_TOKEN }}
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

